services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URI: postgresql://postgres:postgres@postgres/market?sslmode=disable
      ACCRUAL_SYSTEM_ADDRESS: accrual:8080
    command: ["/scheduler"]