name: gophermart

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.24

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env variables
        run: |
          echo "ACCRUAL_HOST=localhost" >> $GITHUB_ENV
          echo "ACCRUAL_PORT=$(random unused-port)" >> $GITHUB_ENV
          echo "POSTGRES_URI=postgresql://postgres:postgres@postgres/praktikum?sslmode=disable" >> $GITHUB_ENV

      - name: Install PostgreSQL client
        run: apt-get update && apt-get install --yes --no-install-recommends postgresql-client

      - name: Load migrations
        run: psql -d postgresql://postgres:postgres@postgres/praktikum?sslmode=disable -f init.sql
        working-directory: ./migrations

      - name: Download autotests binaries
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: "*"
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools
          mv $GITHUB_WORKSPACE/.tools/gophermarttest /usr/local/bin/gophermarttest
          mv $GITHUB_WORKSPACE/.tools/random /usr/local/bin/random

      - name: Prepare binaries
        run: |
          (cd cmd/gophermart && go build -buildvcs=false -o gophermart)
          (cd cmd/scheduler && go build -buildvcs=false -o scheduler)
          (cd cmd/accrual && chmod +x accrual_linux_amd64)

      - name: Start scheduler
        run: cmd/scheduler/scheduler \\
          -d ${{ env.POSTGRES_URI }} \
          -r ${{ env.ACCRUAL_HOST }}:${{ env.ACCRUAL_PORT }} \
        background: true

      - name: Test
        run: |
          gophermarttest \
            -test.v -test.run=^TestGophermart$ \
            -gophermart-binary-path=cmd/gophermart/gophermart \
            -gophermart-host=localhost \
            -gophermart-port=8080 \
            -gophermart-database-uri=${{ env.POSTGRES_URI }} \
            -accrual-binary-path=cmd/accrual/accrual_linux_amd64 \
            -accrual-host=${{ env.ACCRUAL_HOST }} \
            -accrual-port=${{ env.ACCRUAL_PORT }} \
            -accrual-database-uri=${{ env.POSTGRES_URI }}
